Code Generation:
  trigger:
    include: .gitlab-ci.codegen.yml
    strategy: depend
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

ros-noetic:
  trigger:
    include:
      - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml
    strategy: depend
  variables:
    PLATFORM: amd64,arm64
    TARGET: dev,run
    IMAGE_TAG: ros-noetic
    BASE_IMAGE: rwthika/ros:noetic
    COMMAND: roslaunch etsi_its_conversion converter.ros1.launch
    ENABLE_INDUSTRIAL_CI: 'true'
    ENABLE_RECURSIVE_VCS_IMPORT: 'false'

ros2-humble:
  trigger:
    include:
      - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml
    strategy: depend
  variables:
    PLATFORM: amd64,arm64
    TARGET: dev,run
    IMAGE_TAG: ros2-humble
    BASE_IMAGE: rwthika/ros2:humble
    COMMAND: ros2 launch etsi_its_conversion converter.launch.py
    ENABLE_INDUSTRIAL_CI: 'true'
    ENABLE_RECURSIVE_VCS_IMPORT: 'false'

ros2-jazzy:
  trigger:
    include:
      - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml
    strategy: depend
  variables:
    PLATFORM: amd64,arm64
    TARGET: dev,run
    IMAGE_TAG: ros2-jazzy
    ENABLE_PUSH_AS_LATEST: 'true'
    BASE_IMAGE: rwthika/ros2:jazzy
    COMMAND: ros2 launch etsi_its_conversion converter.launch.py
    ENABLE_INDUSTRIAL_CI: 'true'
    ENABLE_RECURSIVE_VCS_IMPORT: 'false'
