include:
  - project: 'forge-tools/asn2md'
    file: '/gitlab-ci/base.yml'

variables:
  ASN1_SRC: 'CAM-PDU-Descriptions.asn cdd/ETSI-ITS-CDD.asn'

validate:
  extends: .validate

documentation:
  extends: .documentation
