etsi_its_conversion:
  ros__parameters:
    has_btp_destination_port: true
    btp_destination_port_offset: 8  # default for Cohda Wireless MK-5 exampleETSI application
    etsi_message_payload_offset: 78 # default for Cohda Wireless MK-5 exampleETSI application
    ros2udp_etsi_types:
      - cam
      - cam_ts
      - cpm_ts
      - denm
      - vam_ts
    udp2ros_etsi_types:
      - cam
      - cpm_ts
      - denm
      - vam_ts
    subscriber_queue_size: 10
    publisher_queue_size: 10
    check_constraints_before_encoding: false # setting to true could lead to segmentation faults because of infinite recursion (https://github.com/vlm/asn1c/issues/410)
